### ISSUE TITLE
Language Validation Error

### ISSUE THREAD

**Issue by 7xrobin** [hwhang0917/ql-movie-api#3]
Hi,
I am trying to run the project locally. I added the .env as in the instructions, but when trying to run I got this error:

`Error: Config validation error: "LANGUAGE" must be one of [AB, AA, AF, AK, SQ, AM, AR, AN, HY, AS, AV, AE, AY, AZ, BM, BA, ...]`

It seems related to the validation of the configuration module:

```
LANGUAGE: Joi.string()
          .valid(...ISO639)
```

Could you help me to solve it?
I am not familiar with Nest.js but would like to use the API.

**Comment by hwhang0917** [comment]
Hi 👋 ,

Thanks for taking interest in this project. 
It's been a while since I've worked on this project so there are still rooms for improvements. 

As the error indicates the `LANGUAGE` field in `.env` file must be one of Alpha-2 Language codes in the given array.
For instance, if you are to use English language from United States region the `.env` configuration would be as following:

```
TMDB_API_KEY="issued-tmdb-api-key"
LANGUAGE="EN"
REGION="US"
```
Both `LANGUAGE` and `REGION` should be Alpha-2 codes.
